### ISSUE TITLE
Race conditions when updating orders

### ISSUE THREAD

**Issue by AndreasPetersen** [mKaloer/Feer-Club#17]
When updating orders, race conditions can occur. The loser takes it all.

**Comment by mKaloer** [comment]
Please elaborate and describe steps to reproduce.

**Comment by AndreasPetersen** [comment]
1. Open the edit page for a beer in two seperate browser windows
2. Make seperate changes in each window
3. Submit in one window
4. Submit in the other window

The last to submit will have their changes persisted. This applies to all update pages.

I would say the problem is that there is no indication that someone else may have changed the same item while one self was in the process of updating an item.
